services:
  grafana:
    profiles: ["grafana"]
    image: vortex-grafana
    build:
      context: .
      dockerfile: Dockerfile
      args:
        GRAFANA_VERSION: ${GRAFANA_VERSION:-11.2.3}
    restart: unless-stopped
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_USER=${GRAFANA_ADMIN_USER:-admin}
      - GF_SECURITY_ADMIN_PASSWORD=${GRAFANA_ADMIN_PASSWORD:-admin}
    volumes:
      - grafana-data:/var/lib/grafana

volumes:
  grafana-data:
