services:
  promtail:
    profiles: ["promtail"]
    image: vortex-promtail
    build:
      context: .
      dockerfile: Dockerfile
      args:
        PROMTAIL_VERSION: ${PROMTAIL_VERSION:-3.2.1}
    restart: unless-stopped
    volumes:
      - /var/log:/var/log:ro
      - ./promtail-config.yml:/etc/promtail/config.yml:ro
    command: -config.file=/etc/promtail/config.yml
    depends_on:
      - loki
